# example with I/Q refclks on CLK1 and CLK2 at 146.520Mhz at 100% power
ref 25000000
mult 20
sleep 500

chan 1
sleep 500
mode point
freq 146520000
phase 0
power 100%

sleep 200

chan 2
sleep 500
mode point
freq 146520000
phase 90
power 100%

sleep 200

# Set up 10Mhz refclk on CLK3
chan 3
sleep 500
mode point
freq 10000000
phase 0
power 0

sleep 200

# Set up 25Mhz refclk on CLK4
chan 4
sleep 500
mode point
freq 25000000
phase 0
power 0
sleep 200

# Exit
quit
